name: Deploy Django to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          cd /home/ubuntu/DRF-Backend
          git pull origin main
          source venv/bin/activate
          pip install -r requirements.txt
          sudo systemctl daemon-reload
          sudo systemctl restart gunicorn
          sudo systemctl restart nginx
